### ISSUE TITLE
Changer model event

### ISSUE THREAD

**Issue by antobrines** [Curlied/Back#25]
Remplacer la clé users en users_waiting et users_validated

**Comment by ferrere-fabrice** [comment]
@antobrines étant donnée que la demande réalisée par @BeatlesBOB était essentiellement orienté autour de ces tests d'implémentation du design, cette fonctionnalité a été implémenté _**partiellement et uniquement**_ sur un évènement de la collection events (bocuse) ce qui a permis de répondre au besoin immédiat.


### Concernant l'avenir
Pour cette modification, il faudrait suite à la modification du model mongo, que souhaiterais tu faire ( pour le moins d'impact collectif)  ?

1. Supprimer les événements avec les anciens schémas et recréer un jeu de test valide. 

ou

2. Repasser sur tous les événements (jeu de test) pour les modifier.


Je préconise la première solution afin de repartir sur des bases seines et cela nous évitera une tâches chronophage, bien que je reste ouvert à d'autres solutions.

**Comment by antobrines** [comment]
Le première clairement ça sera beaucoup plus simple !

**Comment by ferrere-fabrice** [comment]
Super !
