### ISSUE TITLE
Créer route pour modifier un utilisateur

### ISSUE THREAD

**Issue by jemerardprete** [Curlied/Back#26]
Modification du nom d'utilisateur, de la date de naissance, du niveau ynov, de la formation ynov, du téléphone et de la description

**Comment by ferrere-fabrice** [comment]
@jemerardprete 

1. ### Concernant Route 1 : 

> Modification des informations d'un utilisateur (nom d'utilisateur, date de naissance, niveau ynov, formation ynov, email, téléphone, description)

J'ai implémenté en partie cette fonctionnalité dans ma PR [ici](https://github.com/Curlied/Back/pull/28) qui est un mix de plusieurs tâches réalisées et dépendant les unes des autres.

La modification est possible via la méthode PUT à l'adresse :  [http://localhost:3000/api/users](http://localhost:3000/api/users)

Par contre les seules données que j'autorise à la modification sont : 

- username
- telephone
- birth_date

L'email est également obligatoire dans la requête mais sert en élément de sécurité.

![Image](https://user-images.githubusercontent.com/91497720/209483417-f4f59019-c6f8-4b66-9ffe-5cc829b0d5f3.png)

### ℹ Remarque: 
Il est vrai qu'on peut rajouter la description je l'ai oublié ! Souhaite tu la rajouté ?


### ⚠ Compléments :
Concernant les données :

- niveau ynov, 
- formation ynov,


Ce ne sont pas des données avec lesquels nous travaillons pour le moment, souhaites tu les implémentés ? 

Si oui, cela veut dire que notre projet est destiné seulement à Ynov,  es ce bien le résultat attendu ? 

Au besoin je t'implémente tout cela rapidement si besoin.

2. ### Concernant Route 2 : 

> Modification du mot de passe

Cela n'est pas encore implémenté côté back, mais peut être fait rapidement. 

Il faudra prévoir cependant  une interface côté front dédiée uniquement à ça et qui demande l'ancien mot de passe, le nouveau et sa confirmation. Cela nous permettra de travailler en sécurité et de pouvoir fournir un comportement sain. 

Si le front valide le système (je ne pense pas qu'il y ai d'autres choix), serait-il possible de créer à cette fonctionnalité son propre ticket ?

**Comment by jemerardprete** [comment]
**1. ROUTE 1**

Ok top si c'est déjà fait en parti !

Pour l'email : Dans ces cas là, nous allons te créer un nouvel issue

ℹ **Pour la remarque :**
Effectivement, il faudrait également pouvoir modifier la description d'un utilisateur

⚠ **Pour les compléments :**
Dans un premier temps, on avait dit que l'objectif était de rendre Curlied accessible seulement aux étudiants d'Ynov. Donc le designer et moi-même pensions qu'il était pertinent d'ajouter les deux informations suivantes : niveau ynov et formation ynov

**2. ROUTE 2**

L'interface a déjà été imaginée sur la maquette par le designer. C'est noté, un nouvel issue sera crée pour cette fonctionnalité
