### ISSUE TITLE
Ajouter une route pour accepter un utilisateur dans son événement

### ISSUE THREAD

**Issue by jemerardprete** [Curlied/Back#49]

**Comment by vysahjk** [comment]
@antobrines  cette tâche elle n'est pas déjà faites ?

event.route.js

![image](https://user-images.githubusercontent.com/9481712/219033471-9623afd1-e1a8-47be-b1a0-92e2579281f3.png)

**Comment by antobrines** [comment]
@vysahjk Cette route c'est pour rejoindre un évènement, il aura un statut 'en attente' il faut que le owner de l'event puisse l'accepter ou non et ça ce n'est pas fait
