### ISSUE TITLE
Ajouter “.vscode”, “build”, “dist” dans le .gitignore

### ISSUE THREAD

**Issue by antobrines** [Curlied/Back#6]
- [ ] Ajouter “.vscode”, “build”, “dist” dans le .gitignore

**Comment by vysahjk** [comment]
Hello, j'aimerais bien faire cette tâche, mais j'arrive pas à l'assignée à moi même
Bonne soirée

**Comment by antobrines** [comment]
Hey @vysahjk !
C'est fait !
Pour la première tâche ne t'en occupe pas ! On verra ça plus tard car on est pas encore sûr de vouloir le faire étant donné que nous utilisons mongoose qui fait comme un repository !
